### ISSUE TITLE
NativeFileDialog signal file_selected does not fire on FILE_MODE_OPEN_FILE

### ISSUE THREAD

**Issue by tonebacas** [98teg/NativeDialogs#10]
The signal file_selected does not fire when you set the NativeFileDialog file mode to FILE_MODE_OPEN_FILE, and double-click a valid file.
However, the signal files_selected *does* fire under the condition mentioned above.

Also, the signal file_selected *does* fire when you set file mode to FILE_MODE_SAVE_FILE.

I think the signal firing conditions, and the signal naming should be revised, since there is a lot of ambiguity and confusion around them.

I propose the following:
* fire a signal called "save_file_selected" when you're in FILE_MODE_SAVE_FILE, and save a file;
* fire a signal called "file_selected" when you're in FILE_MODE_OPEN_FILE, and select a single file;
* fire a signal called "files_selected" when you're in FILE_MODE_OPEN_FILES, and select multiple files;

**Comment by 98teg** [comment]
You are right, I'm not taking into consideration the mode selected when emitting the event. I would change it so that it depends on the selected mode:
  * `FILE_MODE_OPEN_FILE` would fire `file_selected`.
  * `FILE_MODE_OPEN_FILES` would fire `files_selected`.

However, I would stick to the naming convention, since I'm using the same as Godot's `FileDialog`.
