### ISSUE TITLE
Support for web dialogs

### ISSUE THREAD

**Issue by shafnaz** [98teg/NativeDialogs#30]
Very nice addon!

Would it be possible to create native dialogs for web export?

**Comment by 98teg** [comment]
Hi! Thank you for your kind words!

The web is a very different platform compared to a native OS. For example, on a desktop application, you use a file dialog to get a file path, and then you use that file path to write or read a file. On the web that's not possible, you ask a user for the data of a file, not the file path. Or you provide data to the browser to start a download.

It is because of these fundamental differences that you must consider both platforms differently, and my addon can not provide the same API for both. Here is a plugin that helps you upload a file in the browser:

https://github.com/Scrawach/godot-file-access-web

**Comment by shafnaz** [comment]
I understand. looks like a server would have to come into play

**Comment by 98teg** [comment]
No, not really. You can ask the user to upload a file, then manipulate it in the browser, and finally download it. You need to use the JavaScriptBridge or find an addon that uses it like the one above.
